FROM python:3.12-slim

# Установим системные зависимости
RUN apt-get update && apt-get install -y --no-install-recommends \
    libopenblas-dev \
    libffi-dev \
    postgresql-common \
    libpq-dev \
    libpq5 \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Обновим pip и установим PyTorch CPU-only и нужные библиотеки
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir \
    torch --index-url https://download.pytorch.org/whl/cpu 
    
RUN pip install numpy \
    pandas \
    psycopg \
    yfinance \
    pykalman \
    scikit-learn \
    psycopg_pool


WORKDIR /code


COPY . .

CMD [ "python", "./main.py", "download" ]
